#########
# An Atlas of the Human Liver Cancer Microbiome
# Rahbari, Springer, Zwang et al. (2024)
# Parameters file for visualization
# by Fabian Springer
########

plotting:
        CTRL: "darkgrey"
        HCC: "#62008c"
        iCCA: "#266d07"
        BTC: "#266d07"
        CRLM: "#fa7c0c"
        "HCC/iCCA": "#22B5D3"
        GBC: "#bdbf00"
        "phCCA/dCCA": "#fe8b02"  

        
        responder: "#237B37"
        non-responder: "#FF7F00"

        Adj. non-tumor_iCCA: "#65d03d"
        Adj. non-tumor_CRLM: "#fef400"

        HBV_HCC: "#65d03d"
        HCV_HCC: "#0012fa"
        ALD/ASH_HCC: "#fef400"        
        MAFLD/MASH_HCC: "#ff6600"
        viral_HCC: "#00d989"
        non-viral_HCC: "#fa7c0c"

        TCGA: "#FFBB78"
        DKFZ: "#FF9896"
        ISMMS-IDIBAPS: "#60A960"
        INSERM: "#0841A3"
        "5R16S": "#C58757"