#########
# An Atlas of the Human Liver Cancer Microbiome
# Rahbari, Springer, Zwang et al. (2024)
# Parameters file for visualization
# by Fabian Springer
########

plotting:
        CTRL: "darkgrey"
        HCC: "#62008c"
        iCCA: "#266d07"
        BTC: "#266d07"
        CRLM: "#fa7c0c"
        "HCC/iCCA": "#22B5D3"
        GBC: "#bdbf00"
        "phCCA/dCCA": "#fe8b02"  

        
        responder: "#237B37"
        non-responder: "#FF7F00"

        Adj. non-tumor_iCCA: "#65d03d"
        Adj. non-tumor_CRLM: "#fef400"
        Adj. non-tumor_HCC: "#CBA3D8"

        HBV_HCC: "#65d03d"
        HCV_HCC: "#0012fa"
        ALD/ASH_HCC: "#fef400"        
        MAFLD/MASH_HCC: "#ff6600"
        viral_HCC: "#00d989"
        non-viral_HCC: "#fa7c0c"

        Liver fibrosis early stage: "#f9d75f"
        Liver fibrosis late stage: "#f97a50"
        Fibrosis early stage: "#f9d75f"
        Fibrosis late stage: "#f97a50"

        TCGA: "#FFBB78"
        DKFZ: "#FF9896"
        ISMMS-IDIBAPS: "#60A960"
        INSERM: "#0841A3"
        "5R16S": "#C58757"
        INSERM_1: "#82C0F8"        
        INSERM_2: "#548ADD"
        INSERM_3: "#2665CC"
        INSERM_4: "#AEC7E8"
        INSERM_6: "#3D78D4"        
        INSERM_5: "#0F53C4"        
        INSERM_7: "#6B9DE6"        
        ISMMS-IDIBAPS_1: "#7CC67C"
        ISMMS-IDIBAPS_2: "#98DF8A"
